version: "3.8"
services:
  app:
    build: .
    container_name: news-ai-app
    ports:
      - "18080:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      # Optional manual override. Leave unset to auto-detect location.
      - LOCATION_NAME=${LOCATION_NAME}
      - MIN_ARTICLES_PER_RUN=${MIN_ARTICLES_PER_RUN:-10}
      - TZ=${TZ:-America/New_York}
      - SCHEDULE_MORNING=${SCHEDULE_MORNING:-07:30}
      - SCHEDULE_NOON=${SCHEDULE_NOON:-12:00}
      - SCHEDULE_EVENING=${SCHEDULE_EVENING:-19:30}
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://host.docker.internal:11434}
      - FEED_EXTRA_URLS=${FEED_EXTRA_URLS:-}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - ./data:/data
    restart: unless-stopped

  tts:
    image: synesthesiam/opentts:latest
    container_name: news-ai-tts
    environment:
      # Limit to light, local voices; Piper is CPU-friendly
      - OPENTTS_ENGINES=piper
    volumes:
      - ./data/tts:/root/.local/share/opentts
    expose:
      - "5500"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: news-ai-nginx-ssl
    depends_on:
      - app
    ports:
      # Expose HTTPS on a free high port (not 443)
      - "18443:443"
    volumes:
      - ./nginx/news-ai.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs:/etc/nginx/certs
    environment:
      # Optional: customize cert CN and SANs via env override if desired
      - SSL_CN=news-ai.local
      - SSL_SAN=DNS:news-ai.local,DNS:localhost
    command: >-
      sh -lc "set -e; apk add --no-cache openssl >/dev/null 2>&1 || true; mkdir -p /etc/nginx/certs; if [ ! -f /etc/nginx/certs/server.crt ] || [ ! -f /etc/nginx/certs/server.key ]; then echo 'Generating self-signed cert...'; openssl req -x509 -nodes -newkey rsa:2048 -batch -keyout /etc/nginx/certs/server.key -out /etc/nginx/certs/server.crt -days 365 -subj \"/CN=$${SSL_CN}\"; fi; exec nginx -g 'daemon off;'"
    restart: unless-stopped

