name: news_ai_app
description: Local News & Weather Android App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # HTTP & Networking
  http: ^1.1.0
  dio: ^5.4.0
  
  # Storage
  shared_preferences: ^2.2.2
  
  # Audio
  audioplayers: ^5.2.1
  
  # WebView
  webview_flutter: ^4.4.2
  
  # URL Launcher
  url_launcher: ^6.2.2
  
  # Date Formatting
  intl: ^0.18.1
  
  # HTML Rendering
  flutter_html: ^3.0.0-beta.2
  
  # Path Provider (for logs)
  path_provider: ^2.1.1
  
  # UI
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

